.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GENMKFILE" "8" "January 2020" "genmkfile" "genmkfile Manual"
.SH "NAME"
\fBgenmkfile\fR \- generic make file
.SH "SYNOPSIS"
\fBgenmkfile\fR profile\-name
.SH "DESCRIPTION"
usr/share/genmkfile/Makefile
.SH "EXAMPLE"
\fBsudo genmkfile onionshare\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
